openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /image/image/uncolorization/users/:
    get:
      operationId: read_users_image_image_uncolorization_users__get
      responses:
        200:
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Read Users
  /image/image/uncolorization/users/me:
    get:
      operationId: read_user_me_image_image_uncolorization_users_me_get
      responses:
        200:
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Read User Me
      tags:
      - users
  /image/image/uncolorization/users/{username}:
    post:
      operationId: read_user_image_image_uncolorization_users__username__post
      parameters:
      - explode: false
        in: path
        name: username
        required: true
        schema:
          title: Username
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema: {}
          description: Successful Response
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Read User
      tags:
      - us
  /:
    get:
      operationId: root__get
      responses:
        200:
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
