version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run:
        command: cd api && sh build_and_push dev
        no_output_timeout: 30m

     # deploy the image
     - run:
        command: cd api && sh build_and_push prod
        no_output_timeout: 30m
