version: "3"

services:
  gladia:
    image: "gladiaio/gladia:latest"
    ports:
      - 8080:80
    volumes:
      - $PWD:/app
    environment:
      - TRITON_SERVER_URL=0.0.0.0:${TRITON_SERVER_PORT_HTTP}
      - TRITON_LAZY_DOWNLOAD=false
      - TRITON_MODELS_PATH=/tmp/gladia/triton
    container_name: gladia
