version: "3"

services:
  gladia:
    image: ${GLADIA_SERVICE_IMAGE}
    ports:
      - ${GLADIA_SERVICE_PORT}:80
    volumes:
      - triton-models:/tmp/gladia/triton
      - $PWD:/app
    environment:
      - TRITON_SERVER_URL=triton:${TRITON_SERVER_PORT}
      - TRITON_LAZY_DOWNLOAD=false
      - TRITON_MODELS_PATH=/tmp/gladia/triton
    container_name: ${GLADIA_SERVICE_CONTAINER_NAME}

  triton:
    image: "nvcr.io/nvidia/tritonserver:22.04-py3"
    ports:
      - ${TRITON_SERVER_PORT}:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - triton-models:/models
    command: tritonserver --model-repository=/models --exit-on-error=false --model-control-mode=explicit
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  triton-models: