version: "3"

services:
    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "${PWD}/traefik/prod:/etc/traefik"
        networks: 
            - web
    
    apis:
        build: .
        container_name: "apis"
        volumes:
            - ".:/app"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.apis.rule=Host(`the-deep-learning-project.eu`)"
            - "traefik.http.routers.apis.entrypoints=https"
            - "traefik.http.services.apis.loadbalancer.server.port=8081"
            - "traefik.http.routers.apis.tls=true"
            - "traefik.http.routers.apis.tls.certresolver=letsencrypt"
        expose:
            - 8081
        networks:
            - web

networks:
    web:
        name: web
        driver: bridge
