version: "3.3"

services:
    traefik:
        image: "traefik:v2.2"
        container_name: "traefik"
        command:
            # - --log.level=DEBUG
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.myresolver.acme.dnschallenge=true
            - --certificatesresolvers.myresolver.acme.dnschallenge.provider=ovh
            # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --certificatesresolvers.myresolver.acme.email=contact@paperswithapi.com
            - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        environment:
            - TZ=Europe/Paris
            - OVH_ENDPOINT=ovh-eu
            - OVH_APPLICATION_KEY=l6aqdgqlbBzrV6vh
            - OVH_APPLICATION_SECRET=NylynlyjrTv60sSRvVlSezbBoPPjsId3
            - OVH_CONSUMER_KEY=mkG3g4VH6qWQy8DlB3U3shv8c2MBNSB8
        volumes:
            - ./letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks: 
            - web

    apis:
        build: .
        container_name: "apis"
        volumes:
            - ".:/app"
        labels:
            - traefik.enable=true
            - traefik.http.routers.apis.rule=Host(`paperswithapi.com`)
            - traefik.http.routers.apis.entrypoints=websecure
            - traefik.http.routers.apis.tls.certresolver=myresolver
            - traefik.http.services.apis.loadbalancer.server.port=80
        networks: 
            - web

networks: 
    web:
        name: web
        driver: bridge
        