version: "3"

services:
    traefik:
        image: traefik:v2.4
        container_name: traefik
        command:
            #- "--log.level=DEBUG"
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ${PWD}/traefik/dev:/etc/traefik
        networks: 
            - web
    
    apis:
        build: .
        container_name: apis
        volumes:
            - .:/app
        labels:
            - traefik.enable=true
            - traefik.http.routers.apis.entrypoints=http
            - traefik.http.services.apis.loadbalancer.server.port=80
        expose:
            - 80
        networks:
            - web

networks:
    web:
        name: web
        driver: bridge
