name: Issue Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
    
jobs:
  triage:
    runs-on: [self-hosted, linux, STD]
    steps:
    - uses: github/issue-labeler@v2.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
