name: PR Labeler
on:
  pull_request:
    types: [opened, edited]
    
jobs:
  triage:
    runs-on: [self-hosted, linux, STD]
    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
